SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS comuna (
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO comuna (id, nombre) VALUES
(1,  'Santiago'),
(2,  'Cerrillos'),
(3,  'Cerro Navia'),
(4,  'Conchalí'),
(5,  'El Bosque'),
(6,  'Estación Central'),
(7,  'Huechuraba'),
(8,  'Independencia'),
(9,  'La Cisterna'),
(10, 'La Florida'),
(11, 'La Granja'),
(12, 'La Pintana'),
(13, 'La Reina'),
(14, 'Las Condes'),
(15, 'Lo Barnechea'),
(16, 'Lo Espejo'),
(17, 'Lo Prado'),
(18, 'Macul'),
(19, 'Maipú'),
(20, 'Ñuñoa'),
(21, 'Pedro Aguirre Cerda'),
(22, 'Peñalolén'),
(23, 'Providencia'),
(24, 'Pudahuel'),
(25, 'Quilicura'),
(26, 'Quinta Normal'),
(27, 'Recoleta'),
(28, 'Renca'),
(29, 'San Joaquín'),
(30, 'San Miguel'),
(31, 'San Ramón'),
(32, 'Vitacura'),
(33, 'Puente Alto'),
(34, 'San Bernardo'),
(35, 'Buin'),
(36, 'Calera de Tango'),
(37, 'Paine'),
(38, 'Pirque'),
(39, 'San José de Maipo'),
(40, 'Colina'),
(41, 'Lampa'),
(42, 'Tiltil'),
(43, 'Melipilla'),
(44, 'Alhué'),
(45, 'Curacaví'),
(46, 'María Pinto'),
(47, 'San Pedro'),
(48, 'Talagante'),
(49, 'El Monte'),
(50, 'Isla de Maipo'),
(51, 'Padre Hurtado'),
(52, 'Peñaflor');
